from schemas.pipeline_state import PipelineState
from langchain_core.messages import SystemMessage, HumanMessage
import re
import json
import config.constants as constants

# ---------- Graph B: Skills Specialization
def skills_node(state: PipelineState):
    _a1 = state.get("agent_1_cv_parsing") or {}
    if not _a1 or not _a1.get("summary"):
        return {"agent_2_specialize_skills": {
            "explicit_skills": [],
            "implicit_skills": [],
        }}
    summary = _a1.get("summary", "")
    experience = _a1.get("experience", [])
    education = _a1.get("education", [])
    projects = _a1.get("projects", [])
    reference_skills = _a1.get("skills", [])
    total_experience = _a1.get("total_experience") or "No professional work experience"

    system_prompt = """
    You are a specialized AI agent whose role is to identify and classify skills 
    from text into explicit and implicit categories."""

    skill_extractor_prompt = f"""
    Your task is to analyse the given document and produce a skill profile for the candidate.

    The candidate's explicitly stated skills are already known:
    EXPLICIT SKILLS (already extracted — do NOT regenerate this list):
    {reference_skills}

    CANDIDATE SUMMARY (generated by the CV parser — use this as primary context for seniority and sector assessment):
    {summary}

    TOTAL PROFESSIONAL EXPERIENCE: {total_experience}

    Rule-based instructions:
    1. "skill_summary": Write exactly 3 sentences covering ALL of the following points in order:
         Sentence 1 — Seniority level: Using the CANDIDATE SUMMARY and TOTAL PROFESSIONAL EXPERIENCE above as your
                      primary input, estimate the overall seniority level (Junior / Mid-level / Senior) and briefly
                      justify it referencing the experience duration and skill breadth
                      (e.g. "Based on 2 years of experience and skills spanning X and Y, the candidate is assessed as Junior.").
                      If total experience is "No professional work experience", classify as Junior / Fresh Graduate.
         Sentence 2 — Skill overview & sector fit: Give a high-level overview of the explicit and implicit skills and
                      identify the industry or field sector(s) the candidate is most suited to.
         Sentence 3 — Achievable roles: State the specific job positions or roles the candidate can realistically
                      achieve, grounded in both their explicit and implicit skills.
    2. "implicit_skills": List skills that can be reasonably inferred from the duties, responsibilities, or context of
       the document but are NOT already in the explicit skills list above. For each inferred skill, include a short
       one-line evidence note explaining the reasoning.
    3. If no implicit skills are found, return an empty list for that field.

    Document:
    ---START---
    experience: {experience}
    education: {education}
    projects: {projects}
    ---END---

    Return ONLY valid JSON (no extra commentary).
    {{
  "skill_summary": "3 sentences: (1) seniority level + justification, (2) skill overview + sector fit, (3) achievable roles.",
  "implicit_skills": [
    {{"skill": "skillX", "evidence": "one-line evidence"}},
    {{"skill": "skillY", "evidence": "one-line evidence"}}
    ]
    }}
    """
    
    system_message = SystemMessage(content=system_prompt)
    human_message = HumanMessage(content=skill_extractor_prompt)

    response = constants.llm.invoke([system_message, human_message])
    skill_extractor_raw = response.content

    try:
        skill_extractor_json_text = re.search(r"\{.*\}", skill_extractor_raw, re.S).group(0)
        skill_extractor_json_obj = json.loads(skill_extractor_json_text)
        print("INFO: Skills listed successfully.")
    
    except Exception:
        skill_extractor_json_obj = {
            "skill_summary": "",
            "implicit_skills": []
            }
        print("ERROR: Skills failed to be listed.")

    # explicit_skills is always taken directly from Agent 1's reference skills
    skill_extractor_json_obj["explicit_skills"] = reference_skills
    skill_extractor_json_obj["_raw"] = skill_extractor_raw
    skill_extractor_json_obj["_raw_input"] = skill_extractor_prompt
    return {"agent_2_specialize_skills": skill_extractor_json_obj}